---
name: hello-world
on:
  push:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: action/checkout@v2
      - name: print hello world
        run: echo "hello-world"
